[package]
name = "ersha-dispatch"
version = "0.1.0"
edition = "2024"

[dependencies]
ersha-core = { path = "../ersha-core" } 
ulid = "1.1"
async-trait = "0.1"
jiff = "0.2.18"
rusqlite = { version = "0.38.0", features = ["bundled"] }
serde_json = "1"
tokio = { version = "1", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tempfile = "3.24.0"

